services:
  app:
    build: .
    image: node_nig-viz
    #ports:
    #  - "5173:5173"
    depends_on:
      - mongodb
    environment:
      - SERVER=backend

  mongodb:
    image: mongo:8.2
    restart: always
    volumes:
      - datastore:/data/db      
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      #- MONGO_INITDB_DATABASE=nig-viz

volumes:
  datastore:
