services:
  model:
    build: ./Model
    image: model-slim
    depends_on:
      - backend

  front:
    build: .
    image: node_nig-viz
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - SERVER=dev

  backend:
    build: .
    image: node_nig-viz
    ports:
      - "3030:3030"
    depends_on:
      - mongodb
    environment:
      - SERVER=backend

  mongodb:
    #image: mongo:8.2
    image: mongodb/mongodb-community-server
    restart: always
    volumes:
      - datastore:/data/db      

volumes:
  datastore:


